# Generated by Django 3.0.3 on 2020-03-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_lesson_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='interests',
            field=models.ManyToManyField(to='myapp.Subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='preference',
            field=models.ManyToManyField(to='myapp.Lesson'),
        ),
    ]
